// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzUtw5g8JxoxZXHyf2hngIFhKsXi9LySg',
    appId: '1:959794669657:web:e361333fcb326946a46948',
    messagingSenderId: '959794669657',
    projectId: 'appdelveryabdullas',
    authDomain: 'appdelveryabdullas.firebaseapp.com',
    storageBucket: 'appdelveryabdullas.appspot.com',
    measurementId: 'G-RVLSNZW774',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkaY7DG9wlTEkAj0wBs9oa6mYphvO62Jg',
    appId: '1:959794669657:android:d9e86745bfd02475a46948',
    messagingSenderId: '959794669657',
    projectId: 'appdelveryabdullas',
    storageBucket: 'appdelveryabdullas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDne7XzgXddAyHbKooGE8MxWng3BKqvtkI',
    appId: '1:959794669657:ios:d3b24dc822b981aca46948',
    messagingSenderId: '959794669657',
    projectId: 'appdelveryabdullas',
    storageBucket: 'appdelveryabdullas.appspot.com',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDne7XzgXddAyHbKooGE8MxWng3BKqvtkI',
    appId: '1:959794669657:ios:d3b24dc822b981aca46948',
    messagingSenderId: '959794669657',
    projectId: 'appdelveryabdullas',
    storageBucket: 'appdelveryabdullas.appspot.com',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzUtw5g8JxoxZXHyf2hngIFhKsXi9LySg',
    appId: '1:959794669657:web:e361333fcb326946a46948',
    messagingSenderId: '959794669657',
    projectId: 'appdelveryabdullas',
    authDomain: 'appdelveryabdullas.firebaseapp.com',
    storageBucket: 'appdelveryabdullas.appspot.com',
    measurementId: 'G-RVLSNZW774',
  );
}
